SELECT * FROM dbo.BUNDLES
WHERE BDL_SYS_ID = '467';

UPDATE dbo.BUNDLES
SET CREATE_DATE = CURRENT_TIMESTAMP
WHERE BDL_SYS_ID = '467';

SELECT * FROM dbo.BUNDLES
WHERE BDL_SYS_ID in ('169', '170', '171');

DECLARE @DATE INT
SET @DATE = CAST(GETDATE() AS INT)
SELECT CAST(@DATE AS datetime);

